### PR TITLE
Inline and delay require calls

### PR DESCRIPTION
**Pull request by janwirth**
@ivankravchenko I had to inline these calls for the online demo I created today. Is this fine?

### CODE REVIEW

**Comment by janwirth** [comment]
Tests are running

**Comment by janwirth** [comment]
bump @ivankravchenko http://pug2php.netlify.com/

**Comment by ivankravchenko** [comment]
Hi @FranzSkuffka!
It's probably fine, but why would you need to inline `require`s?

**Comment by janwirth** [comment]
Using browserify I had to make the require calls lazier as they invoke `fs.readFileSync` and the `fs` object is not available in the browser environment. The solution in this PR is not that good because we have some redundancy now. As you are familiar with the architecture, which approach do you suggest?

**Comment by ivankravchenko** [comment]
:+1:

**Pull request merged**
